---
title: "Untitled"
format: html
---

```{r}
library(readr)
library(sf)
library(dplyr)
library(ggplot2)
```
#StepA
```{r}
wildschwein_BE <- read_delim("Data/wildschwein_BE_2056.csv", ",")#Load data

wildschwein_BE$TierName |> unique()

sabi <- wildschwein_BE |>
  filter(TierName == "Sabi")|>
  filter (DatetimeUTC >= as.POSIXct("2015-07-01", tz = "UTC"), DatetimeUTC <as.POSIXct("2015-07-03", tz = "UTC"))
sabi

ggplot (sabi, aes (E, N, color = DatetimeUTC))+
  geom_point()+
  geom_path()+
  coord_equal()


sabi |>
  head(50)|>
  ggplot(aes(DatetimeUTC, 1))+
  geom_point()

sabi <- sabi |>
    mutate(
      n_plus1 = sqrt ((lead(E, 1) - E)^2 + (lead(N, 1)-N)^2), #steplenght 1
      n_plus2 = sqrt ((lead(E, 2) - E)^2 + (lead(N, 2)-N)^2),#steplenght2 forward
      nMinus1 = sqrt((lag(E, 1) - E)^2 + (lag(N, 1) - N)^2),# distance to pos -15 minutes
      nMinus2 = sqrt((lag(E, 2) - E)^2 + (lag(N, 2) - N)^2)# distance to pos -30 minutes
)

sabi <- sabi |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, n_plus1, n_plus2))
    ) |>
    ungroup()# to undo the grouping by row
   

ggplot(sabi, aes(stepMean))+
  geom_histogram(binwidth = 10)+
  geom_vline(xintercept = mean(sabi$stepMean), na.rm = TRUE)
  
sabi |> 
  mutate(static = stepMean < mean(stepMean, na.rm = TRUE))|>
  ggplot(aes(E, N))+
  geom_path()+
    geom_point(aes(color = static))+
                 coord_fixed()
    
```
#with posmo data


```{r}
library("readr")
library("sf")

posmo_K <- read_delim("Data/posmo_data.csv")
head(posmo_K)
posmo_K <- select(posmo_K, datetime, lon_x, lat_y)#To select only this three columns in the dataframe


posmo_K <- st_as_sf(posmo_K,
    coords = c("lon_x", "lat_y"),
    crs = 4326
)#transforms the data frame into a sf object
posmo_K
posmo_K <- st_transform(posmo_K, 2056)#convert the coordinate system to CH1903+ LV95: EPSG:2056

#To be able to compute euclidean distances by hand, we need the coordinates stored in separate columns. The function st_coordinates extracts the coordinates from our sf object. 
posmoK_coordinates <- st_coordinates(posmo_K)

#We can bind these coordinates back to our sf object using cbind
posmo <- cbind(posmo_K, posmoK_coordinates)

#Explore your data and choose a single day for the next steps.
unique(posmo$datetime)

posmo_filter <- posmo |>
    filter(as.Date(datetime) == "2023-03-21")
 
```
#Task1. Segmentation

```{r}
posmo_segmented <- posmo_filter |>
    mutate(
      n_plus1 = sqrt ((lead(X, 1) - X)^2 + (lead(Y, 1)-Y)^2), #steplenght 1
      n_plus2 = sqrt ((lead(X, 2) - X)^2 + (lead(Y, 2)-Y)^2),#steplenght2 forward
      nMinus1 = sqrt((lag(X, 1) - X)^2 + (lag(Y, 1) - Y)^2),# steplenght 1 backward
      nMinus2 = sqrt((lag(X, 2) - X)^2 + (lag(Y, 2) - Y)^2)# steplenght 2 backward
)

 posmo  |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, n_plus1, n_plus2))
    ) |>
    ungroup()# to undo the grouping by row

```


